CREATE TABLE dmgcp-del-171.testdata.dataplex_demo (
    id INT64,
    name STRING,
    age INT64,
    email STRING,
    created_at TIMESTAMP
);

INSERT INTO dmgcp-del-171.testdata.dataplex_demo (id, name, age, email, created_at) VALUES
    (1, "Alice Johnson", 25, "alice.johnson@example.com", CURRENT_TIMESTAMP()),
    (2, "Bob Smith", 30, "bob.smith@example.com", CURRENT_TIMESTAMP()),
    (3, "Charlie Brown", 22, "charlie.brown@example.com", CURRENT_TIMESTAMP()),
    (4, "David Wilson", 28, "david.wilson@example.com", CURRENT_TIMESTAMP()),
    (5, "Emma Watson", 26, "emma.watson@example.com", CURRENT_TIMESTAMP()),
    (6, "Frank Miller", 35, "frank.miller@example.com", CURRENT_TIMESTAMP()),
    (7, "Grace Hall", 29, "grace.hall@example.com", CURRENT_TIMESTAMP()),
    (8, "Henry Adams", 31, "henry.adams@example.com", CURRENT_TIMESTAMP()),
    (9, "Isla Young", 27, "isla.young@example.com", CURRENT_TIMESTAMP()),
    (10, "Jack Turner", 24, "jack.turner@example.com", CURRENT_TIMESTAMP()),
    (11, "Katie Walker", 33, "katie.walker@example.com", CURRENT_TIMESTAMP()),
    (12, "Liam Harris", 29, "liam.harris@example.com", CURRENT_TIMESTAMP()),
    (13, "Mia Scott", 23, "mia.scott@example.com", CURRENT_TIMESTAMP()),
    (14, "Noah King", 26, "noah.king@example.com", CURRENT_TIMESTAMP()),
    (15, "Olivia Wright", 30, "olivia.wright@example.com", CURRENT_TIMESTAMP()),
    (16, "Paul Baker", 28, "paul.baker@example.com", CURRENT_TIMESTAMP()),
    (17, "Quinn Foster", 27, "quinn.foster@example.com", CURRENT_TIMESTAMP()),
    (18, "Ryan Carter", 35, "ryan.carter@example.com", CURRENT_TIMESTAMP()),
    (19, "Sophia Evans", 22, "sophia.evans@example.com", CURRENT_TIMESTAMP()),
    (20, "Tom Green", 32, "tom.green@example.com", CURRENT_TIMESTAMP()),
    (21, "Uma Nelson", 24, "uma.nelson@example.com", CURRENT_TIMESTAMP()),
    (22, "Victor Allen", 29, "victor.allen@example.com", CURRENT_TIMESTAMP()),
    (23, "Wendy Parker", 31, "wendy.parker@example.com", CURRENT_TIMESTAMP()),
    (24, "Xander Mitchell", 33, "xander.mitchell@example.com", CURRENT_TIMESTAMP()),
    (25, "Yara Brooks", 28, "yara.brooks@example.com", CURRENT_TIMESTAMP()),
    (26, "Zane Edwards", 26, "zane.edwards@example.com", CURRENT_TIMESTAMP()),
    (27, "Alice Martin", 22, "alice.martin@example.com", CURRENT_TIMESTAMP()),
    (28, "Brandon Moore", 30, "brandon.moore@example.com", CURRENT_TIMESTAMP()),
    (29, "Chloe White", 29, "chloe.white@example.com", CURRENT_TIMESTAMP()),
    (30, "Dylan Lopez", 31, "dylan.lopez@example.com", CURRENT_TIMESTAMP()),
    (31, "Ethan Carter", 34, "ethan.carter@example.com", CURRENT_TIMESTAMP()),
    (32, "Fiona Murphy", 25, "fiona.murphy@example.com", CURRENT_TIMESTAMP()),
    (33, "George Reed", 27, "george.reed@example.com", CURRENT_TIMESTAMP()),
    (34, "Hannah Bailey", 32, "hannah.bailey@example.com", CURRENT_TIMESTAMP()),
    (35, "Ian Rogers", 29, "ian.rogers@example.com", CURRENT_TIMESTAMP()),
    (36, "Julia Cooper", 23, "julia.cooper@example.com", CURRENT_TIMESTAMP()),
    (37, "Kyle Stewart", 28, "kyle.stewart@example.com", CURRENT_TIMESTAMP()),
    (38, "Laura Bell", 26, "laura.bell@example.com", CURRENT_TIMESTAMP()),
    (39, "Michael James", 30, "michael.james@example.com", CURRENT_TIMESTAMP()),
    (40, "Natalie Howard", 31, "natalie.howard@example.com", CURRENT_TIMESTAMP()),
    (41, "Owen Scott", 29, "owen.scott@example.com", CURRENT_TIMESTAMP()),
    (42, "Paige Hughes", 27, "paige.hughes@example.com", CURRENT_TIMESTAMP()),
    (43, "Quentin Bryant", 35, "quentin.bryant@example.com", CURRENT_TIMESTAMP()),
    (44, "Rebecca Morgan", 22, "rebecca.morgan@example.com", CURRENT_TIMESTAMP()),
    (45, "Samuel Ward", 33, "samuel.ward@example.com", CURRENT_TIMESTAMP()),
    (46, "Tara Richardson", 28, "tara.richardson@example.com", CURRENT_TIMESTAMP()),
    (47, "Ulysses Simmons", 31, "ulysses.simmons@example.com", CURRENT_TIMESTAMP()),
    (48, "Violet Peterson", 24, "violet.peterson@example.com", CURRENT_TIMESTAMP()),
    (49, "William Russell", 26, "william.russell@example.com", CURRENT_TIMESTAMP()),
    (50, "Xavier Griffin", 30, "xavier.griffin@example.com", CURRENT_TIMESTAMP()),
    (51, "Yvonne Cooper", 27, "yvonne.cooper@example.com", CURRENT_TIMESTAMP()),
    (52, "Zachary Nelson", 32, "zachary.nelson@example.com", CURRENT_TIMESTAMP()),
    (53, "Adam Ford", 25, "adam.ford@example.com", CURRENT_TIMESTAMP()),
    (54, "Bella Harrison", 29, "bella.harrison@example.com", CURRENT_TIMESTAMP()),
    (55, "Charlie Foster", 31, "charlie.foster@example.com", CURRENT_TIMESTAMP()),
    (56, "Daisy Freeman", 28, "daisy.freeman@example.com", CURRENT_TIMESTAMP()),
    (57, "Edward Butler", 26, "edward.butler@example.com", CURRENT_TIMESTAMP()),
    (58, "Faith Jenkins", 30, "faith.jenkins@example.com", CURRENT_TIMESTAMP()),
    (59, "Gavin Reed", 27, "gavin.reed@example.com", CURRENT_TIMESTAMP()),
    (60, "Holly Powell", 35, "holly.powell@example.com", CURRENT_TIMESTAMP()),
    (61, "Isaac Crawford", 22, "isaac.crawford@example.com", CURRENT_TIMESTAMP()),
    (62, "Jackie Barnes", 24, "jackie.barnes@example.com", CURRENT_TIMESTAMP()),
    (63, "Kevin Bates", 31, "kevin.bates@example.com", CURRENT_TIMESTAMP()),
    (64, "Luna West", 29, "luna.west@example.com", CURRENT_TIMESTAMP()),
    (65, "Mason Perry", 30, "mason.perry@example.com", CURRENT_TIMESTAMP()),
    (66, "Nancy Jenkins", 26, "nancy.jenkins@example.com", CURRENT_TIMESTAMP()),
    (67, "Oscar Hall", 32, "oscar.hall@example.com", CURRENT_TIMESTAMP()),
    (68, "Pamela Brooks", 27, "pamela.brooks@example.com", CURRENT_TIMESTAMP()),
    (69, "Quincy Rivera", 29, "quincy.rivera@example.com", CURRENT_TIMESTAMP()),
    (70, "Riley Stevens", 34, "riley.stevens@example.com", CURRENT_TIMESTAMP());
